type AverageHour {
  type: String
  name: String
  duration: Int
  formattedDuration: String
}

type Query {
  averageHours(
    startDate: DateScalar!
    endDate: DateScalar!
    type: String!
  ): [AverageHour]
}
