type Project {
  _id: ID!
  name: String!
  area: String!
}

type Query {
  projects: [Project]!
  project(_id: ID!): Project
}

input ProjectInput {
  name: String!
  area: String!
}

input ProjectUpdate {
  name: String!
  area: String!
}

type Mutation {
  createProject(data: ProjectInput!): Project!
  deleteProject(_id: ID!): ID!
  updateProject(_id: ID!, data: ProjectUpdate!): Project!
}
