type CompiledMember {
  sessions: [Session]!
  aditionalHours: [AditionalHour]!
  """
  A soma total da duração dos valores retornados em milisegundos
  """
  total: Int!

  """
  A soma total da duração dos valores retornados no formato hh:mm
  """
  formatedTotal: String!
  formatedPresentialTotal: String!
}

type CompiledSessions {
  sessions: [Session]!
  aditionalHours: [AditionalHour]
  formatedTotal: String!
  formatedPresentialTotal: String!
}

type CompiledMandatory {
  sessions: [Session]!
  mandatory: Mandatory!
  expectedDuration: Int!
  duration: Int!
}

type MandatoryReport {
  mandatories: [CompiledMandatory]!
  date: DateScalar!
}

type SessionsReport {
  member: Member!
  # sessions: [Session]
  # sessionsBiggerThan0: [Session]

  """
  A soma total da duração das sessoes em milisegundos
  """
  total: Int!

  """
  A soma total da duração das sessoes retornados no formato hh:mm
  """
  formatedTotal: String!
  formatedPresentialTotal: String!
}

type Query {
  compiled(
    memberId: ID!
    startDate: DateScalar
    endDate: DateScalar
  ): CompiledMember!

  allMembersSessions(
    startDate: DateScalar
    endDate: DateScalar
    compileGroup: Int
  ): [SessionsReport]!

  getMandatoriesReport(
    memberId: ID!
    startWeekYear: Int!
    startWeeknumber: Int!
    endWeekYear: Int!
    endWeeknumber: Int!
  ): [MandatoryReport]!

  allSessions(
    startDate: DateScalar
    endDate: DateScalar
    taskIds: [ID]
    projectIds: [ID]
    tribeIds: [ID]
    memberIds: [ID]
    departamentIds: [ID]
  ): CompiledSessions!
}
