type News {
  _id: String!

  """
  String que guarda o HTML da noticia
  """
  html: String!

  """
  Posição da notícia
  """
  index: Int

  """
  Id inteiro da notícia gerado pelo front-end
  """
  numberId: Int
}

input NewsInput {
  _id: String

  html: String!
  index: Int!
  numberId: Int!
}

type Query {
  news: [News]!
}

type Mutation {
  createNews(data: NewsInput!): News!
  replaceNews(data: [NewsInput]!): [News]!
  deleteNews(newsId: ID!): Boolean
  uploadImage(file: Upload!, numberId: Int!): String!
}
