type News {
  _id: String!

  """
  String que guarda o HTML da noticia
  """
  html: String!

  """
  Posição da notícia
  """
  index: Int

  """
  Id String da notícia gerado pelo front-end
  """
  newsId: ID
}

input NewsInput {
  _id: String

  html: String!
  index: Int!
  newsId: ID!
}

type Query {
  news: [News]!
}

type Mutation {
  createNews(data: NewsInput!): News!
  replaceNews(data: [NewsInput]!): [News]!
  deleteNews(newsId: ID!): Boolean
  uploadImage(file: Upload!, newsId: ID!): String!
}
