type Badge {
    _id: ID!
    name: String!
    description: String!
    url: String!
}

type Query {
    badges: [Badge]!
    badge(_id: ID!): Badge
}

input BadgeInput {
    name: String!
    description: String!
    url: String!
}

input BadgeUpdate {
    name: String
    description: String
    url: String
}

type Mutation {
    createBadge(data: BadgeInput!): Badge!
    deleteBadge(badgeId: ID!): Badge
    updateBadge(badgeId: ID, data: BadgeUpdate): Badge
}