type Student{
    _id: ID!
    name: String!
    # note: Note!
}

type Query {
    students: [Student]!
    student(id: ID!): Student!
}

input StudentInput {
    name: String!
    # note: ID
}

type Mutation {
  createStudent(data: StudentInput!): Student!
  deleteStudent(studentId: ID!): Boolean
  updateStudent(studentId: ID, data: StudentInput): Student!
}
