type Student{
    _id: ID!
    name: String!
}

type Query {
    students: [Student]!
    student(_id: ID!): Student!
}

input StudentInput {
    name: String!
}

type Mutation {
  createStudent(data: StudentInput!): Student!
  deleteStudent(studentId: ID!): Boolean
  updateStudent(studentId: ID, data: StudentInput): Student!
}
