type Member {
  _id: ID!
  firebase_id: String
  name: String!
  status: String
  role_id: ID
  image_link: String
  responsible_id: Member
  responsible: Member
}

type Query {
  members: [Member]!
  membersByResponsible(responsible_id: ID!): [Member]!
  member(_id: ID!): Member
}

input MemberInput {
  name: String!
  status: String
  role_id: ID
  img_link: ID
  responsible_id: ID
  firebase_id: String
}

type Mutation {
  createMember(data: MemberInput): Member!
  updateMember(id: ID, data: MemberInput): Member!
  deleteMember(id: ID): Boolean
}
