type Member {
  _id: ID!
  firebaseId: String
  name: String!
  """
  Mensagem de status de login
  """
  status: String
  roleId: ID
  role: Role
  imageLink: String
  responsibleId: ID
  responsible: Member
  """
  Mensagem do acompanhamento
  """
  message: String
  mandatories: [Mandatory]!
}

type Mandatory {
  """
  Hora de inicio em milisegundos do horário obrigatório
  """
  startAt: Int!
  """
  Hora de fim em milisegundos do horário obrigatório
  """
  endAt: Int!
  weekDay: Int!
}

type Query {
  members: [Member]!
  membersByResponsible(responsibleId: ID!): [Member]!
  member(_id: ID!): Member
}

input MandatoryInput {
  """
  Hora de inicio em milisegundos do horário obrigatório
  """
  startAt: Int!
  """
  Hora de fim em milisegundos do horário obrigatório
  """
  endAt: Int!
  weekDay: Int!
}

input MemberInput {
  firebaseId: String
  name: String!
  status: String
  roleId: ID
  imgLink: ID
  responsibleId: ID
  message: String
}

input MemberUpdate {
  name: String
  status: String
  roleId: ID
  imgLink: ID
  responsibleId: ID
  message: String
}

type LoginData {
  accessToken: ID
  member: Member!
}

type Mutation {
  login(tokenId: ID!): LoginData!
  getSessionData: LoginData!
  createMember(data: MemberInput): Member!
  """
  Atualiza campos de um usuário, o usuário deve ter a permissão para realizar essa ação.
  """
  updateMember(memberId: ID, data: MemberUpdate!): Member!

  """
  Atualiza campos do propio usuário logado, retorna um novo access token.
  """
  updateSelf(data: MemberUpdate!): LoginData!

  deleteMember(memberId: ID!): Member
  addMandatory(memberId: ID!, data: MandatoryInput): Member!
  removeMandatory(memberId: ID!, mandatoryId: ID!): Boolean!
}
