type Role {
  _id: ID!
  name: String!
  access: Int!
}

type Query {
  Roles: [Role]!
}

input RoleInput {
  name: String!
  access: Int!
}

type Mutation {
  createRole(data: RoleInput!): Role!
  deleteRole(roleId: ID!): Boolean!
}
