type Role {
  _id: ID!
  name: String!
  access: Int!
}

type Query {
  roles: [Role]!
}

input RoleInput {
  name: String!
  access: Int!
}

input RoleUpdate {
  name: String
  access: Int
}

type Mutation {
  createRole(data: RoleInput!): Role!
  deleteRole(roleId: ID!): Role
  updateRole(roleId: ID, data: RoleUpdate): Role
}
