type Role {
  _id: ID!
  name: String!
  access: Int!
  departamentId: ID
  departament: Departament
}

type Query {
  roles: [Role]!
}

input RoleInput {
  name: String!
  access: Int!
  departamentId: ID
}

input RoleUpdate {
  name: String
  access: Int
  departamentId: ID
}

type Mutation {
  createRole(data: RoleInput!): Role!
  deleteRole(roleId: ID!): Role
  updateRole(roleId: ID!, data: RoleUpdate): Role
}
