type Notification {
  _id: ID!
  text: String!
  link: String!
  linkValidation: String!
}

type Query {
  notifications: [Notification!]!
}

type Mutation {
  createNotification(
    text: String!
    link: String!
    linkValidation: String!
  ): Notification!
  deleteNotification(_id: ID!): Notification
  getUserList(sheetID: String!, userName: String!): Notification
}
