type Color {
  _id: ID!
  primaryColor: String!
  secundaryColor: String!

}
type Query {
  colors: [Color]!
  color(_id: ID!): Color
}

input ColorInput {
  primaryColor: String!
  secundaryColor: String!
}

input ColorUpdate {
  primaryColor: String!
  secundaryColor: String!
}
type Mutation {
  createColor(data: ColorInput!): Color!
  deleteColor(colorId: ID!): Color
}