type Note {
    _id: ID!
    text: String!
}

type Query {
    note(_id: ID!): Note!
}

input NoteInput {
    text: String!
}

type Mutation {
  createNote(data: NoteInput!): Note!
  deleteNote(noteId: ID!): Note
  updateNote(noteId: ID, data: NoteInput): Note!
}
